# .github/workflows/build.yml
name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Jenkins
        run: echo "Triggered via GitHub webhook"
